vim.api.nvim_set_keymap('n', '<Leader>gs', ':Git<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>gd', ':Gdiff<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>gl', ':diffget //2<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>gr', ':diffget //3<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>gc', ':Git difftool --name-status<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>gb', ':Git blame<CR>', { noremap = true })
